apps/contato/urls.py
from django.urls import path, re_path

from .views import ContatoFormView

app_name = 'contato'

urlpatterns = [
    path('', ContatoFormView.as_view(), name='contato'),
]

gsa/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.home import urls as home_urls
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView
from apps.servicos import urls as servicos_urls
from apps.ronda import urls as ronda_urls
from apps.gerador_qrcode import urls as qr_url
from apps.apontamento import urls as apontamento_url
from apps.contato import urls as contato_url

from django.conf import settings


urlpatterns = [
    path('tinymce/', include('tinymce.urls')),
    path('contato/', include(contato_url)),
    path('apontamento/', include(apontamento_url)),
    path('qr/', include(qr_url)),
    path('dashboard/', include(ronda_urls)),
    path('servicos/',  include(servicos_urls)),
    path('accounts/', include('django.contrib.auth.urls')),
    path('',  include(home_urls)),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls))
    )

apps/contato/models.py
from django.db import models
from apps.base.models import BaseModelSlug, BaseModelUUID
from apps.servicos.models import Servico
from apps.core.signals import create_slug
from django.db.models import signals


class Departamento(BaseModelUUID):
    nome = models.CharField('Departamento', max_length=30)
    ativo = models.BooleanField('Ativo?', default=True)

    def __str__(self):
        return self.nome


class Contato(BaseModelSlug):
    nome = models.CharField('Nome', max_length=60)
    whatsapp = models.CharField('Whatsapp', max_length=20)
    email = models.EmailField('E-mail')
    departamento = models.CharField("Departamento", max_length=30)
    mensagem = models.TextField('Mensagem')
    notificacao_whatsapp = models.BooleanField(
        'Deseja, Receber Informações de novidades dos nossos serviços por whatsapp', default=False)
    notificacao_email = models.BooleanField('Deseja, Receber Informações de novidades dos nossos serviços por email',
                                            default=False)
    slug_from = 'nome'

    def __str__(self):
        return f"Contato: {self.nome}"


signals.post_save.connect(create_slug, sender=Contato)

apps/contato/forms.py
from django import forms
from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV2Checkbox
from .models import Contato, Departamento


class ContatoForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ContatoForm, self).__init__(*args, **kwargs)


        self.fields['departamento'] = forms.CharField(label="Departamento", max_length=30,
                                                      widget=forms.Select(choices=self.get_servicos()))
        self.fields['captcha'] = ReCaptchaField(widget=ReCaptchaV2Checkbox())

    def get_servicos(self):
        items = Departamento.objects.filter(ativo=True).values('nome')
        choice = []
        for item in items:
            choice.append(
                (item['nome'].replace(' ', '').capitalize(), item['nome'].title()))
        return choice

    def send_email(self):
        # send email using the self.cleaned_data dictionary
        pass

    class Meta:
        model = Contato
        fields = '__all__'

apps/contato/views.py
from django.views.generic.edit import CreateView
from django.contrib.messages.views import SuccessMessageMixin
from apps.core.envio_email import SendGSAMail
from .forms import ContatoForm
from .models import Contato


class ContatoFormView(SuccessMessageMixin, CreateView):
    model = Contato
    template_name = 'contato/contato_form.html'
    form_class = ContatoForm
    success_url = '/contato/'
    success_message = "%(nome)s , Mensagem enviada com sucesso!"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['active_contato'] = True
        return context

    def form_valid(self, form):
        subject = form.cleaned_data.get('departamento')
        nome = form.cleaned_data.get('nome')
        email = form.cleaned_data.get('email')
        whatsapp = form.cleaned_data.get('whatsapp')
        mensagem = form.cleaned_data.get('mensagem')

        email_mensagem = SendGSAMail(subject, nome, mensagem, whatsapp)
        email_mensagem.contato(servico=subject, email=email)

        return super().form_valid(form)

templates/contato/contato_form.html
{% extends  'home/base_detalhe.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
    <div class="container-fluid bg-light overflow-hidden px-lg-0">
        <div class="container contact px-lg-0">
            <div class="row g-0 mx-lg-0">
                <div class="col-lg-6 contact-text py-5 wow fadeIn" data-wow-delay="0.5s">
                    <div class="p-lg-5 ps-lg-0">
                        <div class="section-title text-start">
                            <h1 class="display-5 mb-4">Formulário de Contato</h1>
                        </div>
                        <form method="post">
                            {% with WIDGET_ERROR_CLASS='errors' WIDGET_REQUIRED_CLASS='required' %}
                                {% csrf_token %}
                                <div class="row g-3">
                                    <div class="col-md-6">
                                        <div class="form-floating required">
                                            {% render_field form.nome|append_attr:"class:form-control" type="text"%}
                                            <label for="nome">Seu Nome</label>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-floating">
                                            {% render_field form.email|append_attr:"class:form-control" type="email" %}
                                            <label for="email">Seu Email</label>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-floating">
                                            {% render_field form.whatsapp|append_attr:"class:form-control" type="text" %}
                                            <label for="nome">Seu Whatsapp</label>
                                        </div>
                                    </div>

                                    <div class="col-12">
                                        <div class="form-floating">
                                            {% render_field form.departamento|append_attr:"class:form-control" %}
                                            <label for="subject">Departamento</label>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="form-floating">
                                            {% render_field form.mensagem|append_attr:"class:form-control"|append_attr:"cols:50"|append_attr:"rows:50" pattern="\([0-9]{2}\)[\s][0-9]{4}-[0-9]{4,5}" %}
                                            <label for="message">Mensagem</label>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="col-md-12">
                                            <div class=" form-check">

                                                <label for="notificacao_whatsapp">
                                                    {% render_field form.notificacao_whatsapp %}
                                                    Desejo Receber notificações dos serviços por whatsapp

                                                </label>
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class=" form-check">

                                                <label for="notificacao_whatsapp">
                                                    {% render_field form.notificacao_email %}
                                                    Desejo Receber notificações dos serviços por email

                                                </label>
                                            </div>
                                        </div>
                                        <div class="col-md-12 form-group">
                                            {% render_field form.captcha  class="form-control" %}
                                        </div>
                                        <button class="btn btn-primary w-100 py-3" type="submit">Enviar Mensagem
                                        </button>
                                    </div>
                                </div>
                            {% endwith %}
                        </form>
                    </div>
                </div>
                <div class="col-lg-6 pe-lg-0" style="min-height: 400px;">
                    <div class="position-relative h-100">
                        <iframe class="position-absolute w-100 h-100" style="object-fit: cover;"
                                src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3679.6582812410334!2d-46.89781564982495!3d-22.74093923761731!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94c8dea28bebc435%3A0x21cfc62d6881eebf!2sAv.%20Papa%20Jo%C3%A3o%20XXIII%2C%207%2C%20Pedreira%20-%20SP%2C%2013920-000!5e0!3m2!1spt-BR!2sbr!4v1664162041700!5m2!1spt-BR!2sbr"
                                frameborder="0" allowfullscreen="" aria-hidden="false"
                                tabindex="0"></iframe>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}
{% block scipts %}

    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery.maskedinput/1.4.1/jquery.maskedinput.min.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-toast-plugin/1.3.2/jquery.toast.css"
          crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-toast-plugin/1.3.2/jquery.toast.min.js"></script>

    <script>
        jQuery("#id_whatsapp")
            .mask("(99) 9999-9999?9")
            .focusout(function (event) {
                var target, phone, element;
                target = (event.currentTarget) ? event.currentTarget : event.srcElement;
                phone = target.value.replace(/\D/g, '');
                element = $(target);
                element.unmask();
                if (phone.length > 10) {
                    element.mask("(99) 99999-999?9");
                } else {
                    element.mask("(99) 9999-9999?9");
                }
            });
    </script>

    <script>
        {% if messages %}
            {% for message in messages %}
                $(function () {
                    $.toast({
                        heading: 'Success',
                        text: '{{ message.message }}',
                        icon: 'success',
                        showHideTransition: 'plain',
                        position: 'top-right',
                        stack: false
                    })

                })
            {% endfor %}
        {% endif %}
    </script>


{% endblock scipts %}