apps/gerador_qrcode/urls.py
from django.urls import path, re_path
from .views import(NovoQrCodeView, ListaQrCodeView, DetalheQrCodeView,
                   ImprimirQrCodeView, DeleteQrCodeView)

app_name = 'qrcode'

urlpatterns = [
    path('novo/', NovoQrCodeView.as_view(), name='novo_qr'),
    path('lista/', ListaQrCodeView.as_view(), name='lista_qr'),
    path('qrcode/<int:pk>/', DetalheQrCodeView.as_view(), name='detalhe_qr'),
    path('imprimir/<int:pk>/', ImprimirQrCodeView.as_view(), name='imprimir_qr'),
    path('delete/<int:pk>/', DeleteQrCodeView.as_view(), name='delete_qr'),
]

gsa/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.home import urls as home_urls
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView
from apps.servicos import urls as servicos_urls
from apps.ronda import urls as ronda_urls
from apps.gerador_qrcode import urls as qr_url
from apps.apontamento import urls as apontamento_url
from apps.contato import urls as contato_url

from django.conf import settings


urlpatterns = [
    path('tinymce/', include('tinymce.urls')),
    path('contato/', include(contato_url)),
    path('apontamento/', include(apontamento_url)),
    path('qr/', include(qr_url)),
    path('dashboard/', include(ronda_urls)),
    path('servicos/',  include(servicos_urls)),
    path('accounts/', include('django.contrib.auth.urls')),
    path('',  include(home_urls)),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls))
    )

apps/gerador_qrcode/models.py
from django.db import models
from django.urls import reverse

from apps.empresas.models import Empresa


class QrCode(models.Model):
    empresa = models.ForeignKey(Empresa, on_delete=models.PROTECT,
                                related_name='empresa_qr',
                                verbose_name='Empresa')
    local = models.CharField('Local', max_length=100)
    qr_code = models.ImageField("QR Code", upload_to='qr-codes', blank=True)
    created_at = models.DateTimeField('Cadastrado em', auto_now_add=True)
    updated_at = models.DateTimeField('Modificado em', auto_now=True)

    def get_absolute_url(self):
        return reverse('ronda:dashboard')

    def __str__(self):
        return self.local

apps/gerador_qrcode/forms.py
from io import BytesIO

import qrcode
from PIL import Image, ImageDraw
from django.core.files import File
from django.forms import ModelForm
from .models import QrCode
from apps.empresas.models import Empresa


class NovoQrCodeForm(ModelForm):
    class Meta:
        model = QrCode
        fields = '__all__'

    def save(self, commit=True, *args, **kwargs):
        instance = super(NovoQrCodeForm, self).save(commit=False)
        empresa = Empresa.objects.get(id=int(self.data['empresa']))
        qr_codeimg = qrcode.make(
            f"{empresa.nome},{self.data['local']}")
        canvas = Image.new('RGB', (300, 300), 'white')
        draw = ImageDraw.Draw(canvas)

        canvas.paste(qr_codeimg)
        fname = f"qr_code-{empresa.nome}_{self.data['local']}.png"

        buffer = BytesIO()
        canvas.save(buffer, 'PNG')
        instance.qr_code.save(fname, File(buffer), save=False)
        canvas.close()
        super().save(*args, **kwargs)

apps/gerador_qrcode/views.py
from django.urls import reverse
from django.contrib import messages
from django.urls import reverse_lazy
from braces.views import PermissionRequiredMixin
from django.views.generic import CreateView, ListView, DetailView, DeleteView
from .models import QrCode
from .forms import NovoQrCodeForm


class NovoQrCodeView(PermissionRequiredMixin, CreateView):
    model = QrCode
    form_class = NovoQrCodeForm
    template_name = 'gerador_qrcode/novo_qrcode.html'
    permission_required = 'global_permissions.colaboradores'

    def get_success_url(self):
        messages.success(self.request, 'Qr Code Criado com Sucesso')
        return reverse('qrcode:lista_qr')



    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['active'] = 'active'
        return context


class ListaQrCodeView(PermissionRequiredMixin, ListView):
    model = QrCode
    paginate_by = 6
    context_object_name = 'qr_codes'
    template_name = 'gerador_qrcode/lista_qrcode.html'
    success_message = "%(local)s criado com sucesso"
    permission_required = 'global_permissions.colaboradores'

    def get_queryset(self):
        return QrCode.objects.all().order_by('-created_at')

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            local=self.object.local,
        )


class DetalheQrCodeView(DetailView):
    model = QrCode
    template_name = 'gerador_qrcode/detalhe.html'


class ImprimirQrCodeView(DetailView):
    model = QrCode
    template_name = 'gerador_qrcode/imprimir.html'


class DeleteQrCodeView(DeleteView):
    model = QrCode
    success_url = reverse_lazy('qrcode:lista_qr')

templates/gerador_qrcode/detalhe.html
{% extends 'core/base.html' %}
{% load static %}

{% block titulo %}
    GSA::{{ object.local }} | {{ object.empresa }}
{% endblock titulo %}

{% block content %}
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Impresssão Qr Code</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">imprimir</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-6">
                        <div class="invoice p-3 mb-3">
                            <!-- title row -->
                            <div class="row">
                                <div class="col-12">
                                    <h4>
                                        <i class="fas fa-globe"></i> GSA Portaria e Serviços.
                                        <small class="float-right">Date: {{ object.created_at.date }}</small>
                                    </h4>
                                </div>
                                <!-- /.col -->
                            </div>
                            <!-- info row -->
                            <div class="row invoice-info">
                                <div class="col-sm-4 invoice-col">
                                    Empresa
                                    <address>
                                        <strong>{{ object.empresa }}</strong><br>
                                    </address>
                                </div>
                                <!-- /.col -->
                                <div class="col-sm-4 invoice-col">
                                    Local
                                    <address>
                                        <strong>{{ object.local }}</strong><br>
                                    </address>
                                </div>
                                <!-- /.col -->
                                <div class="col-sm-4 invoice-col">
                                    <b>ID #{{ object.id }}</b><br>
                                </div>
                                <!-- /.col -->
                            </div>
                            <!-- /.row -->

                            <!-- Table row -->
                            <div class="row">
                                <div class="col-md-12">
                                    <!-- Box Comment -->
                                    <div class="card card-widget">
                                        <div class="card-header">


                                        </div>
                                        <!-- /.card-header -->
                                        <div class="card-body">
                                            <img class="img-fluid pad" src="{{ object.qr_code.url}}" alt="Photo">
                                        </div>
                                        <!-- /.card-body -->

                                    </div>
                                </div>
                                <div class="row no-print">
                                    <div class="col-12">
                                        <a href="{% url 'qrcode:imprimir_qr' object.id %}" rel="noopener" target="_blank" class="btn btn-default"><i class="fas fa-print"></i> Print</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- /.content -->
    </div>
{% endblock content %}

templates/gerador_qrcode/imprimir.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>GSA::{{ object.local }}::{{ object.empresa }}</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'ronda/plugins/fontawesome-free/css/all.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'ronda/dist/css/adminlte.min.css' %}">
</head>
<body>
<div class="wrapper">
    <!-- Main content -->
    <section class="invoice">
        <div class="row">
            <div class="col-6">
                <div class="invoice p-3 mb-3">
                    <!-- title row -->
                    <div class="row">
                        <div class="col-12">
                            <h4>
                                <i class="fas fa-globe"></i> GSA Portaria e Serviços.
                            </h4>
                        </div>
                        <!-- /.col -->
                    </div>
                    <div class="row invoice-info">
                        <div class="col-sm-4 invoice-col">
                            Empresa
                            <address>
                                <strong>{{ object.empresa }}</strong><br>
                            </address>
                        </div>
                        <div class="col-sm-4 invoice-col">
                            Local
                            <address>
                                <strong>{{ object.local }}</strong><br>
                            </address>
                        </div>
                        <!-- /.col -->
                        <div class="col-sm-4 invoice-col">
                            ID
                            <address>
                                <strong>{{ object.id }}</strong><br>
                            </address>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <!-- Box Comment -->
                            <div class="card card-widget">
                                <div class="card-header">
                                </div>
                                <div class="card-body">
                                    <img class="img-fluid pad" src="{{ object.qr_code.url}}" alt="Photo">
                                </div>
                            </div>
                        </div>
                        <div class="row no-print">
                            <div class="col-12">
                                <a href="{% url 'qrcode:imprimir_qr' object.id %}" rel="noopener" target="_blank" class="btn btn-default"><i class="fas fa-print"></i> Print</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- /.content -->
</div>
<!-- ./wrapper -->
<!-- Page specific script -->
<script>
    window.addEventListener("load", window.print());
</script>
</body>
</html>

templates/gerador_qrcode/lista_qrcode.html
{% extends 'core/base.html' %}
{% load static %}

{% block titulo %}
    GSA::Lista de QrCode
{% endblock titulo %}
{% block css %}
<script src="{% static 'ronda/plugins/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'ronda/plugins/sweetalert2/sweetalert2.min.js' %}"></script>
<script src="{% static 'ronda/plugins/toastr/toastr.min.js' %}"></script>


{% endblock %}

{% block content %}
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Qr Codes</h1>
{#                        {% if messages %}#}
{#                            {% for message in messages %}#}
{#                                <script type="text/javascript">#}
{#                                 $(function (){#}
{#                                    $.toast({#}
{#                                        text : "Let's test some HTML stuff... <a href='#'>github</a>",#}
{#                                        showHideTransition : 'slide',  // It can be plain, fade or slide#}
{#                                        bgColor : 'blue',              // Background color for toast#}
{#                                        textColor : '#eee',            // text color#}
{#                                        allowToastClose : false,       // Show the close button or not#}
{#                                        hideAfter : 5000,              // `false` to make it sticky or time in miliseconds to hide after#}
{#                                        stack : 5,                     // `fakse` to show one stack at a time count showing the number of toasts that can be shown at once#}
{#                                        textAlign : 'left',            // Alignment of text i.e. left, right, center#}
{#                                        position : 'bottom-left'       // bottom-left or bottom-right or bottom-center or top-left or top-right or top-center or mid-center or an object representing the left, right, top, bottom values to position the toast on page#}
{#                                    })#}
{#                                     })#}
{#                                </script>#}
{#                                <div class="text-center alert alert-{{ message.tags }}">#}
{#                                    {{ message|safe }}#}
{#                                </div>#}
{#                            {% endfor %}#}
{#                        {% endif %}#}

                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">QR Codes</li>
                        </ol>
                    </div>
                </div>
            </div>
        </section>
        <section class="content">
            <div class="card card-solid">
                <div class="card-body pb-0">
                    <div class="row">
                        {% for qrcode in qr_codes %}
                            <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch flex-column">
                                <div class="card bg-light d-flex flex-fill">
                                    <div class="card-header text-muted border-bottom-0">
                                        {{ qrcode.empresa.nome }}
                                    </div>
                                    <div class="card-body pt-0">
                                        <div class="row">
                                            <div class="col-7">
                                                <h2 class="lead"><b>{{ qrcode.created_at }}</b></h2>
                                                <p class="text-muted text-sm"><b>Local: </b> {{ qrcode.local }} </p>
                                            </div>
                                            <div class="col-5 text-center">
                                                <img src="{{ qrcode.qr_code.url }}" alt="{{ qrcode.empresa.nome }}" class="img-rounded img-fluid">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="card-footer">
                                        <div class="text-right">
                                            <a href="{% url 'qrcode:delete_qr' qrcode.id %}" class="btn btn-sm bg-danger">
                                                <i class="fas fa-trash"></i>
                                            </a>
                                            <a href="{% url 'qrcode:detalhe_qr' qrcode.id %}" class="btn btn-sm btn-primary">
                                                <i class="fas fa-user"></i> Imprimir
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <!-- /.card-body -->
            {% include 'gerador_qrcode/pagination.html' %}
        </section>
    </div>
{% endblock content %}

{% block scripts %}
    <script>
        {% if messages %}
            {% for message in messages %}
                $(function() {
                    $(document).Toasts('create', {
                        closeButton: true,
                        class: 'bg-success',
                        title: 'Criação Qr Code',
                        progressBar: true,
                        hideAfter: 10000,
                        autohide: true,
                        delay: 950,
                        body: '{{ message }}'
                    })
                });
    {% endfor %}
        {% endif %}
</script>
{% endblock scripts %}

templates/gerador_qrcode/novo_qrcode.html
{% extends 'core/base.html' %}
{% load widget_tweaks %}


{% block content %}
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>General Form</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">General Form</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <!-- left column -->
                    <div class="col-md-12">
                        <!-- general form elements -->
                        <div class="card card-primary">
                            <div class="card card-warning">
                                <div class="card-header">
                                    <h3 class="card-title">General Elements</h3>
                                </div>
                                <!-- /.card-header -->
                                <div class="card-body">
                                    <form method="post">{% csrf_token %}
                                        <div class="row">
                                            <div class="col-sm-6">
                                                <!-- text input -->
                                                <div class="form-group">
                                                    <label>{{ form.empresa.label }}</label>
                                                    {% render_field form.empresa|append_attr:"class:form-control" type="text" %}
                                                </div>
                                            </div>
                                            <div class="col-sm-6">
                                                <div class="form-group">
                                                    <label>{{ form.local.label }}</label>
                                                    {% render_field form.local|append_attr:"class:form-control" type="text" placeholder="Local Qr" %}
                                                </div>
                                            </div>
                                             <div class="col-sm-6">
                                                <div class="form-group">
                                                    <label>{{ form.local.qr_code }}</label>
                                                    {{ form.qr_code |attr:"type:file" |add_class:"class:form-control" }}
                                                </div>
                                            </div>
                                        </div>
                                        <div class="card-footer">
                                            <button type="submit" class="btn btn-success">Criar Qr</button>
                                        </div>
                                    </form>
                                </div>
                                <!-- /.card-body -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
{% endblock content %}

templates/gerador_qrcode/pagination.html
<div class="card-footer">
    <nav aria-label="Contacts Page Navigation">
        <ul class="pagination justify-content-center m-0">
            {% for page in paginator.page_range%}
                <li class="page-item {% if page_obj.number == page%}active{% endif %}"><a class="page-link" href="?page={{ page }}{{ getvars }}">{{ page }}</a></li>
             {% endfor %}
        </ul>
    </nav>
</div>

templates/gerador_qrcode/qrcode_confirm_delete.html
{% extends 'core/base.html' %}
{% block titulo %}
    GSA::Delete | {{ object }}
{% endblock titulo %}

{% block content %}
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Deletar :: {{ object }} ?</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Inline Charts</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card card-default">
                            <div class="card-header">
                                <h3 class="card-title">
                                    <i class="fas fa-exclamation-triangle"></i>
                                    Alerts
                                </h3>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <div class="alert alert-danger alert-dismissible">
                                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                    <h5><i class="icon fas fa-ban"></i> Alert!</h5>
                                    <form method="post">{% csrf_token %}
                                        <p>Tem Certeza que deseja Deletar Permanentemente  "{{ object }}"?</p>
                                        {{ form }}
                                        <input type="submit" class="btn btn-warning" value="Confirm">
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
{% endblock content %}