apps/apontamento/urls.py
from django.urls import path
from .views import RegistroNovoView, RegistroListaView, ListaRegistrosView

app_name = 'apontamento'

urlpatterns = [
    path('', ListaRegistrosView.as_view(), name='list_registro'),
    path('registros/', RegistroListaView.as_view(), name='usuario_registro'),
    path('novo/', RegistroNovoView.as_view(), name='novo_registro'),
]

apps/contato/urls.py
from django.urls import path, re_path

from .views import ContatoFormView

app_name = 'contato'

urlpatterns = [
    path('', ContatoFormView.as_view(), name='contato'),
]

apps/home/urls.py
from django.urls import path, re_path
from .views import HomeView


app_name = 'home'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
]

apps/servicos/urls.py
from django.urls import path, re_path
from .views import ServicoDetalhe, ServicosView

app_name = 'servicos'

urlpatterns = [
    path('', ServicosView.as_view(), name='servicos'),
    path('<slug:slug>/', ServicoDetalhe.as_view(), name='servico_detalhe'),
]

gsa/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.home import urls as home_urls
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView
from apps.servicos import urls as servicos_urls
from apps.ronda import urls as ronda_urls
from apps.gerador_qrcode import urls as qr_url
from apps.apontamento import urls as apontamento_url
from apps.contato import urls as contato_url

from django.conf import settings


urlpatterns = [
    path('tinymce/', include('tinymce.urls')),
    path('contato/', include(contato_url)),
    path('apontamento/', include(apontamento_url)),
    path('qr/', include(qr_url)),
    path('dashboard/', include(ronda_urls)),
    path('servicos/',  include(servicos_urls)),
    path('accounts/', include('django.contrib.auth.urls')),
    path('',  include(home_urls)),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls))
    )

apps/home/models.py
from django.db import models
from apps.base.models import BaseModelUUID


class Parceiros(BaseModelUUID):
    ativo = models.BooleanField('Ativo?', default=True)
    nome = models.CharField('Nome', max_length=100)
    logo = models.ImageField('Logo', upload_to='parceiros', default='media/parceiro.jpg')

    class Meta:
        ordering = ["created_at"]
        verbose_name_plural = "Parceiros"

    def __str__(self):
        return self.nome


class Solucoes(BaseModelUUID):
    nome = models.CharField('Solução', max_length=50)
    icone = models.ImageField(upload_to='solucoes/imagens')
    descricao = models.TextField('Soluções')

    def __str__(self):
        return self.nome


class InformacoesDoSite(BaseModelUUID):
    nome = models.CharField('Nome do Site', max_length=25)
    telefone = models.CharField('Telefone', max_length=30)
    email = models.EmailField('e-mail')
    endereco = models.CharField('Endereço', max_length=200)
    facebook = models.URLField('Facebook', null=True, blank=True)
    instagram = models.URLField('Facebook', null=True, blank=True)
    sobre = models.TextField('Sobre', null=True, blank=True)
    escolha = models.TextField('Porque escolher-nos', null=True, blank=True)

    def __str__(self):
        return self.nome

apps/home/views.py
from django.views.generic.base import TemplateView
from apps.servicos.models import Servico, ServicosDestaques, Categoria
from .models import Parceiros


class HomeView(TemplateView):
    template_name = 'home/Home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['carousels_home'] = self.get_carousel()
        context['destaques'] = self.get_destaques()
        context['servicos_home'] = self.get_servicos_home()
        context['parceiros'] = Parceiros.objects.filter(ativo=True)
        context['active_home'] = True
        return context

    def get_carousel(self):
        return Servico.objects.filter(slider=True)

    def get_destaques(self):
        destaques = ServicosDestaques.objects.all()
        cont = 1
        dados = []

        for item in destaques:
            dados.append(
                {
                    "nome": item.nome,
                    "icone": item.icone,
                    "descricao": item.descricao,
                    "style_time": f"0.{cont}s",
                    "numero": cont
                }
            )
            cont += 1

        return dados

    def get_servicos_home(self):
        servicos_home = Servico.objects.filter(ativo=True)[:9]
        cont = 1
        dados = []

        for item in servicos_home:
            dados.append({
                "id": item.id,
                "nome": item.titulo,
                "imagem": item.imagem,
                "categoria": item.categoria,
                "descricao": item.descricao,
                "slug": item.slug,
                "time": f"0.{cont}s"
            })
            cont += 1

        return dados

templates/home/includes/_navbar.html
<nav class="navbar navbar-expand-lg bg-white navbar-light sticky-top p-0 px-4 px-lg-5">
    <a href="{% url 'home:home' %}" class="navbar-brand d-flex align-items-center">
        <h2 class="m-0 text-primary">GSA Portaria</h2>
    </a>
    <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="navbar-nav ms-auto py-4 py-lg-0">
            <a href="{% url 'home:home' %}" class="nav-item nav-link {% if active_home %}active {% endif %}">Home</a>
            <div class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Serviços</a>
                <div class="dropdown-menu rounded-0 rounded-bottom m-0">
                    {% for categoria_servico in categorias_servicos %}
                        <a href="{ categoria_servico.get_absolute_url }}" class="dropdown-item">{{ categoria_servico }}</a>
                    {% endfor %}

                </div>
            </div>
            <a href="{% url 'contato:contato' %}" class="nav-item nav-link {% if active_contato %}active {% endif %}">Contato</a>
            <a href="" class="nav-item nav-link">Login</a>
            <a href="https://www.gsaportaria.com.br:2096/" class="nav-item nav-link">Webmail</a>
        </div>
        <div class="h-100 d-lg-inline-flex align-items-center d-none">
            <a class="btn btn-square rounded-circle bg-light text-primary me-2" href=""><i
                    class="fab fa-facebook-f"></i></a>
            <a class="btn btn-square rounded-circle bg-light text-primary me-2" href=""><i
                    class="fab fa-twitter"></i></a>
            <a class="btn btn-square rounded-circle bg-light text-primary me-2" href=""><i
                    class="fab fa-linkedin-in"></i></a>
            <a class="btn btn-square rounded-circle bg-light text-primary me-0" href=""><i class="fab fa-instagram"></i></a>
        </div>
    </div>
</nav>

templates/home/includes/carousel.html
{% load static %}

<div class="container-fluid p-0 pb-5">
    <div class="owl-carousel header-carousel position-relative">
        <div class="owl-carousel-item position-relative">
            <img class="img-fluid" src="{% static 'home/img/banner_gsa.png' %}" alt="">
            <div class="carousel-inner">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-12 col-lg-8 text-center">
                            <h1 class="display-3 text-white animated slideInDown mb-4">GSA
                                Portaria e
                                Serviços</h1>
                            <p class="fs-5 text-white mb-4 pb-2">Terceirização de Serviços</p>
                            <a href="{% url 'contato:contato' %}"
                               class="btn btn-primary rounded-pill py-md-3 px-md-5 me-3 animated slideInLeft">Orçamento
                            </a>
                            <a href="" class="btn btn-light rounded-pill py-md-3 px-md-5 animated slideInRight">Contato
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% for carousel_h in carousels_home %}
            <div class="owl-carousel-item position-relative">
                <img class="img-fluid" src="{{ carousel_h.imagem.url }}" alt="">
                <div class="carousel-inner">
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-12 col-lg-8 text-center">
                                <h1 class="display-3 text-white animated slideInDown mb-4">{{ carousel_h.titulo }}</h1>
                                <p class="fs-5 fw-medium text-white mb-4 pb-2">{{ carousel_h.descricao| slice:"0:100" }}</p>
                                <a href=""
                                   class="btn btn-primary rounded-pill py-md-3 px-md-5 me-3 animated slideInLeft">Orçamento</a>
                                <a href="{% url 'servicos:servico_detalhe' carousel_h.slug %}" class="btn btn-light rounded-pill py-md-3 px-md-5 animated slideInRight">Saber
                                    Mais</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

templates/home/includes/footer.html
<div class="container-fluid bg-dark text-secondary footer mt-5 py-5 wow fadeIn" data-wow-delay="0.1s">
    <div class="container py-5">
        <div class="row g-5">
            <div class="col-lg-3 col-md-6">
                <h5 class="text-light mb-4">Informações</h5>
                <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>{{ site_infor.endereco }}</p>
                <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>{{ site_infor.telefone }}</p>
                <p class="mb-2"><i class="fa fa-envelope me-3"></i>{{ site_infor.email }}</p>
                <div class="d-flex pt-2">
                    <a class="btn btn-square btn-outline-secondary rounded-circle me-2" href=""><i
                            class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-square btn-outline-secondary rounded-circle me-2" href=""><i
                            class="fab fa-linkedin-in"></i></a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <h5 class="text-light mb-4">Serviços</h5>
                {% for categoria_servico in categorias_servicos %}
                    <a class="btn btn-link" href="{ categoria_servico.get_absolute_url }}"
                       class="dropdown-item">{{ categoria_servico }}</a>
                {% endfor %}
            </div>
            <div class="col-lg-3 col-md-6">
                <h5 class="text-light mb-4">Links Rápidos</h5>
                {#                <a class="btn btn-link" href="">About Us</a>#}
                {#                <a class="btn btn-link" href="">Contact Us</a>#}
                {#                <a class="btn btn-link" href="">Our Services</a>#}
                {#                <a class="btn btn-link" href="">Terms & Condition</a>#}
                {#                <a class="btn btn-link" href="">Support</a>#}
            </div>
            <div class="col-lg-3 col-md-6">
                <h5 class="text-light mb-4">Novidades</h5>
                <p>Cadastre seu email para receber novidades dos nossos serviços</p>
                <div class="position-relative w-100">
                    <input class="form-control bg-transparent border-secondary w-100 py-3 ps-4 pe-5" type="text"
                           placeholder="seu email">
                    <button type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">Enviar
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid py-4" style="background: #000000;">
    <div class="container">
        <div class="row">
            <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                &copy; <a class="border-bottom" href="#">gsaportaria</a>, All Right Reserved.
            </div>
            <div class="col-md-6 text-center text-md-end">
                <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                Designed By <a class="border-bottom" href="https://htmlcodex.com">mod64bits</a><br>Desenvolvido por <a
                    class="border-bottom" href="http://mod64bits.herokuapp.com/">mod64bits</a>
            </div>
        </div>
    </div>
</div>
<!-- Copyright End -->

templates/home/includes/header.html
<header id="header" class="fixed-top ">
    <div class="container d-flex align-items-center">

        <h1 class="logo mr-auto"><a href="{% url 'home:home' %}">GSA</a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html" class="logo mr-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

        <nav class="nav-menu d-none d-lg-block">
            <ul>
                <li class="active"><a href="{% url 'home:home' %}">Home</a></li>
                <li><a href="#about">Sobre nós</a></li>
                <li><a href="#services">Serviços</a></li>
                <li><a href="#portfolio">Portfólio</a></li>
                <li><a href="#team">Parceiros</a></li>
                <li><a href="{% url 'contato:contato' %}">Contato</a></li>
                <li><a href="https://www.gsaportaria.com.br:2096/">Webmail</a></li>
                <li><a href="{% url 'apontamento:usuario_registro' %}">Sistema</a></li>

            </ul>
        </nav><!-- .nav-menu -->

    </div>
</header>

templates/home/includes/servicos_destaques.html
{% load static %}
<div class="container-xxl py-5">
    <div class="container">
        <div class="row g-4">
            {% for destaque in destaques %}
                <div class="col-md-6 col-lg-4 wow fadeIn" data-wow-delay="{{ destaque.style_time }}">
                    <div class="h-100 bg-dark p-4 p-xl-5">
                        <div class="d-flex align-items-center justify-content-between mb-4">
                            <div class="btn-square rounded-circle"
                                 style="width: 64px; height: 64px; background: #000000;">
                                <img class="img-fluid" src="{{ destaque.icone.url }}" alt="Icon">
                            </div>
                            <h1 class="display-1 mb-0" style="color: #000000;">{{ destaque.numero }}</h1>
                        </div>
                        <h5 class="text-white">{{ destaque.nome }}</h5>
                        <hr class="w-25">
                        <span>{{ destaque.descricao }}</span>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>

templates/home/includes/top_bar.html
<div class="container-fluid bg-dark px-5">
    <div class="row gx-4 d-none d-lg-flex">
        <div class="col-lg-6 text-start">
            <div class="h-100 d-inline-flex align-items-center py-3 me-4">
                <div class="btn-sm-square rounded-circle bg-primary me-2">
                    <small class="fa fa-map-marker-alt text-white"></small>
                </div>
                <small>{{ site_infor.endereco }}</small>
            </div>
            <div class="h-100 d-inline-flex align-items-center py-3">
                <div class="btn-sm-square rounded-circle bg-primary me-2">
                    <small class="fa fa-envelope-open text-white"></small>
                </div>
                <small>{{ site_infor.email }}</small>
            </div>
        </div>
        <div class="col-lg-6 text-end">
            <div class="h-100 d-inline-flex align-items-center py-3 me-4">
                <div class="btn-sm-square rounded-circle bg-primary me-2">
                    <small class="fa fa-phone-alt text-white"></small>
                </div>
                <small>{{ site_infor.telefone }}</small>
            </div>
            <div class="h-100 d-inline-flex align-items-center py-3">
                <div class="btn-sm-square rounded-circle bg-primary me-2">
                    <small class="far fa-clock text-white"></small>
                </div>
                <small>24 h</small>
            </div>
        </div>
    </div>
</div>